apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qkr1za03c-nodejs
  janus-idp.io/tekton: qkr1za03c-nodejs
  backstage.io/kubernetes-id: qkr1za03c-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qkr1za03c-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
