apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qkr1za03c-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qkr1za03c-nodejs 
  name: qkr1za03c-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: qkr1za03c-nodejs 
